spring.application.name=spring-data-mongodb

spring.mongodb.uri=mongodb+srv://mohamednagymabrock_db_user:010250mN@cluster0.ushwiml.mongodb.net/spring?retryWrites=true&w=majority&appName=Cluster0

logging.level.org.springframework.data=debug
logging.level.root=error

server.port=9090